---
- name: "Dock - Check if present {{ item }}"
  ansible.builtin.command:
    cmd: dockutil --find '{{ item }}'
  register: dock_item_exists
  changed_when: false
  failed_when: >
    "No such file or directory" in dock_item_exists.stdout
    or "command not found" in dock_item_exists.stdout
  tags: ["dock"]

- name: "Dock - Remove {{ item }}"
  ansible.builtin.command:
    cmd: dockutil --remove '{{ item }}'
  when: dock_item_exists.rc  == 0
  tags: ["dock"]
