---
brew_tap:
  - hashicorp/tap

brew_install:
  - alfred
  - cursor
  - dockutil
  - go
  - golang-migrate
  - google-chrome
  - google-cloud-sdk
  - hashicorp/tap/terraform
  - helm
  - hiddenbar
  - kube-forwarder
  - kubectl
  - libpq
  - mas
  - minikube
  - mkcert
  - nvm
  - openvpn
  - pnpm
  - postman
  - rectangle
  - studio-3t
  - yarn
  - zoom

brew_cask:
  - docker-desktop
  - microsoft-teams
  - notion
