---
- name: Brew - Check if already installed {{ item }}
  ansible.builtin.shell:
    cmd: brew list | grep -q "{{ item }}"
  register: brew_formula_check
  changed_when: false
  failed_when: false
  tags: ["brew"]

- name: Brew - Installing {{ item }}
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  when: not brew_formula_check.rc == 0
  tags: ["brew"]
