---
- name: Brew - Install tap items
  ansible.builtin.include_tasks: tap.yml
  loop: "{{ brew_tap }}"

- name: Brew - Install brew items
  ansible.builtin.include_tasks: brew.yml
  loop: "{{ brew_install }}"

- name: Brew - Install cask items
  ansible.builtin.include_tasks: cask.yml
  loop: "{{ brew_cask }}"
