---
- name: Brew - Check if already installed {{ item }}
  ansible.builtin.shell:
    cmd: brew list | grep -q "{{ item }}"
  register: brew_tap_check
  changed_when: false
  failed_when: false
  tags: ["brew"]

- name: Brew - Configuring tap {{ item }}
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  when: not brew_tap_check.rc == 0
  tags: ["brew"]
