git_repositories:
  - config: config.digibee
    repos:
      - url: git@gitlab.com:digibee-product/platform-governance/auth-management.git
        dest: "~/Git/digibee/auth-management"
      - url: git@gitlab.com:digibee-product/core/pipeline-trigger.git
        dest: "~/Git/digibee/pipeline-trigger"
      - url: git@gitlab.com:digibee-product/components/default-collection-core.git
        dest: "~/Git/digibee/default-collection-core"
      - url: git@gitlab.com:digibee-product/core/pipeline-engine-light-v2.git
        dest: "~/Git/digibee/pipeline-engine-light-v2"
      - url: git@gitlab.com:digibee-product/core-platforms/pipeline-controller.git
        dest: "~/Git/digibee/pipeline-controller"
      - url: git@gitlab.com:digibee-product/core/digibeectl.git
        dest: "~/Git/digibee/digibeectl"
      - url: git@gitlab.com:digibee-product/core/pipeline-coordinator.git
        dest: "~/Git/digibee/pipeline-coordinator"
      - url: git@gitlab.com:digibee-product/web/digibee-portal-v3.git
        dest: "~/Git/digibee/digibee-portal-v3"
      - url: git@gitlab.com:digibee-product/web/digibee-graphql.git
        dest: "~/Git/digibee/digibee-graphql"
      - url: git@gitlab.com:digibee-product/design-system/digibee-ui.git
        dest: "~/Git/digibee/digibee-ui"
      - url: git@gitlab.com:digibee-product/design-system/beehive.git
        dest: "~/Git/digibee/beehive"
      - url: git@gitlab.com:digibee-product/cloud-engineering/gitops/burner-us.git
        dest: "~/Git/digibee/burner-us"

  - config: config.morelli
    repos:
      - url: "git@github.com:MarcosMorelli/ansible-mac.git"
        dest: "~/Git/marcosmorelli/ansible-mac"
      - url: "git@github.com:MarcosMorelli/smart-poker.git"
        dest: "~/Git/marcosmorelli/smart-poker"
      - url: "git@github.com:MarcosMorelli/react-fe.git"
        dest: "~/Git/marcosmorelli/react-fe"
      - url: "git@github.com:MorelliTec/node-be.git"
        dest: "~/Git/marcosmorelli/node-be"
      - url: "git@github.com:MorelliTec/terraform-infra.git"
        dest: "~/Git/marcosmorelli/terraform-infra"

git_envs:
  - env: "node-be-env"
    dest: "~/Git/marcosmorelli/node-be/.env"
