- name: Git - name
  community.general.git_config:
    scope: global
    name: user.name
    value: "{{ git.name }}"

- name: Git - email address
  community.general.git_config:
    scope: global
    name: user.email
    value: "{{ git.email }}"

- name: Git - override default branch to match with GitHub defaults
  community.general.git_config:
    scope: global
    name: init.defaultBranch
    value: main

- name: Git - auto setup remote
  community.general.git_config:
    scope: global
    name: push.autoSetupRemote
    value: true

- name: Git - Clone repositories
  ansible.builtin.include_tasks: clone_repos.yml
  loop: "{{ git_repositories }}"

- name: Git - Copy envs
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    content: |
      {{ lookup('ansible.builtin.unvault', 'secrets/envs/' ~ item.env ) }}
  loop: "{{ git_envs }}"
