dock_remove:
  - Ajustes do Sistema
  - App Store
  - Apps
  - Calendar
  - Calendário
  - Contacts
  - Contatos
  - Downloads
  - Espelhamento do iPhone
  - FaceTime
  - Fotos
  - Games
  - iPhone Mirroring
  - Jogos
  - Lembretes
  - Mail
  - Mapas
  - Maps
  - Mensagens
  - Messages
  - Music
  - Música
  - Notas
  - Notes
  - Phone
  - Photos
  - Reminders
  - Safari
  - System Settings
  - Telefone
  - TV

dock_items_persist:
  - name: "Cursor"
    path: "/Applications/Cursor.app"
    pos: 1
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app"
    pos: 2
  - name: "Slack"
    path: "/Applications/Slack.app"
    pos: 3
  - name: "WhatsApp"
    path: "/Applications/WhatsApp.app"
    pos: 4
