dockitems_remove:
  - App Store
  - Apps
  - Calendar
  - Contacts
  - Downloads
  - FaceTime
  - Games
  - iPhone Mirroring
  - Mail
  - Maps
  - Messages
  - Music
  - Notes
  - Phone
  - Photos
  - Reminders
  - Safari
  - System Settings
  - TV

dockitems_persist:
  - name: "Cursor"
    path: "/Applications/Cursor.app"
    pos: 1
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app"
    pos: 2
  - name: "Slack"
    path: "/Applications/Slack.app"
    pos: 3
  - name: "WhatsApp"
    path: "/Applications/WhatsApp.app"
    pos: 4
