---
- name: Creates nvm home directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.nvm"
    state: directory

- name: Node - Install versions
  ansible.builtin.include_tasks: install_version.yml
  vars:
    node_version: "{{ item }}"
  with_items: "{{ node_versions_install }}"
