ssh_keys:
  - name: "morelli"
    mode: "0600"
  - name: "morelli.pub"
    mode: "0644"
  - name: "terraform"
    mode: "0600"
  - name: "terraform.pub"
    mode: "0644"

ssh_configs:
  - template: "config.j2"
    dest: "config"
  - template: "config.ccc.j2"
    dest: "config.ccc"
  - template: "config.morelli.j2"
    dest: "config.morelli"
