cursor_extensions:
  - bradlc.vscode-tailwindcss
  - cweijan.dbclient-jdbc
  - cweijan.vscode-mysql-client2
  - eamodio.gitlens
  - esbenp.prettier-vscode
  - golang.go
  - mechatroner.rainbow-csv
  - mongodb.mongodb-vscode
  - tomoki1207.pdf
  - vue.volar
